version: '3.8'

services:
  # WebSocket 聊天服务器
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - PORT=8082
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端静态文件服务器
  chat-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_WS_HOST=localhost  # 前端通过localhost访问WebSocket服务器
      - VITE_WS_PORT=8082
    depends_on:
      - chat-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s